volumes:
  noteTakingApi:
  postgres-db:
  
services:
  postgres:
    container_name: 'note-pg'
    image: 'postgres:17.3'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'noteDb'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    
    

